name: Shell Command
on: [push]
jobs:
    run-shell-command: 
      runs-on: ubuntu-latest
      steps:
        - name: echo a string
          run: echo "I'm batman"
        - name: multiline script
          run: |
            node -v
            npm -v
        - name: python Command
          run: |
            import platform
            print(platform.processor())
          shell: python
    run-windows-command:
       runs-on: windows-latest
       needs: [run-shell-command]
       steps:
         - name: Directoy powershell
           run: Get-Location
         - name: Directoy Bash
           run: pwd
           shell: bash